version: '3.5'

services:

  web:
    image: web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - APP_NAME={{cookiecutter.app_name}}
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=0
      - APP_SETTINGS=project.server.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/users_test
      - SECRET_KEY=change_me_in_prod
    depends_on:
      - web-db

  web-db:
    container_name: web-db
    build:
      context: ./project/server/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
